import {  Montserrat } from "next/font/google";
import { ReactQueryProvider } from "./reactQueryProvider";
import "./globals.css";
import ChatBot from "@/components/ChatBot";
import { Toaster } from "sonner";

const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}`}
      >
        <ReactQueryProvider>
          {children}
          <Toaster position="top-center" />
          <ChatBot />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
